author: pherce
name: FullXP
main: me.pherce.FullXP.FullXP
version: 1.1
description: Players drop full experience on death, now with permissions.

permissions:
    fullxp.grant:
        description: Grants this user the ability to drop their full experience on death.
		default: false